# Generated by Django 5.1.1 on 2024-09-15 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('api_url', models.CharField(max_length=256)),
                ('provider_token', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('template_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VerifyRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_sender', models.CharField(max_length=256)),
                ('system', models.CharField(choices=[('SI', 'SMS.IR'), ('KN', 'KAVENEGAR')], default='SI', max_length=2)),
                ('flag', models.CharField(choices=[('W', 'WAITING'), ('O', 'OnGoing'), ('P', 'PASSED'), ('R', 'ReTry'), ('F', 'Failed')], default='W', max_length=2)),
                ('tries', models.IntegerField(default=0)),
                ('token_value', models.CharField(max_length=255)),
                ('template_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TemplatesEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_code', models.CharField(max_length=256)),
                ('token_keys', models.JSONField()),
                ('engine_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.engine')),
                ('template_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.templates')),
            ],
        ),
    ]
