# Generated by Django 5.1.1 on 2024-09-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifyrequests',
            name='template_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='verifyrequests',
            name='token_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
