# Generated by Django 5.1.1 on 2024-09-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_alter_verifyrequests_template_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifyrequests',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
